---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    open-pull-requests-limit: 50

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50

  - package-ecosystem: npm
    target-branch: dev
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    labels:
      - 'feature / dependency'
    open-pull-requests-limit: 50

  - package-ecosystem: pip
    target-branch: dev
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    labels:
      - 'feature / dependency'
    open-pull-requests-limit: 50
